#!/usr/bin/env bash
# Script for Handle the docker Service

Docker_Menu_Arch(){
while true; do
	echo -e "\e[1;41mChecking Docker Status\e[0m"
	options=("Docker Status"
		"Start Docker"
		"Stop Docker"
		"Return to Previous Menu")
	select opt in "${options[@]}"
	do
		case $opt in
			"Docker Status")
			echo -e "\e[1;41m checking Docker Daemon\e[0m"
			sleep 1
			sudo systemctl status docker
			sleep 1
			break
			;;

			"Start Docker")
			echo -e "\e[1;41m Starting Docker Daemon\e[0m"
			sleep 1
			sudo systemctl start docker 
			echo -e "\e[1;41m Docker Daemon Started\e[0m"
			sleep 1
			break
			;;

			"Stop Docker")
			echo -e "\e[1;41m Stopping Docker Daemon\e[0m"
			sleep 1
			sudo systemctl stop docker 
			echo -e "\e[1;41m Docker Daemon Stopped\e[0m"
			sleep 1
			break
			;;
			
			"Return to Previous Menu")
			break 2
			;;

			*) echo -e "Invalid Option, Try again"
			sleep 1.5
			break
			;;
	

		esac
	done
done
}


Check_Docker(){
while true; do
	echo -e "\e[1;41mChoose your distro wisely\e[0m"
	options=("Ubuntu 16"
		"Arch Linux"
		"Return to previous Menu")
	select opt in "${options[@]}"
	do
		case $opt in
			"ubuntu 16")
			echo -e "\e[1;41m Starting Docker Daemon\e[0m"
			sleep 1
			sudo service docker start
			echo -e "\e[1;41m Docker Daemon Started\e[0m"
			sleep 1
			break 2
			;;

			"Arch Linux")
			Docker_Menu_Arch
			break 2
			;;

			"Return to previous Menu")
			break 2
			;;

			*) echo -e "Invalid Option, Try again"
			sleep 1.5
			break
			;;
			esac
	done
done
}



"$@"


