#!/usr/bin/env bash
# Bash Fucntions to install Common software based on Arch docker Image

Return_Message(){
echo -e "\e[1;37;42mTool Added\e[0m"
sleep 1
echo -e "\e[1;32mIf you want to add some tool more, return to previous menus and hit the option, when you finish, return to previous menu\e[0m"
echo -e "\e[1;32mof pimp my container and choose the let's pimp my image option to build your custom image\e[0m"
sleep 2
}

Common_Arch(){
	while true;do
	echo -e "\e[1;32m*******************\e[0m"
	echo -e "\033[5;32m*  Common tools  *\033[0m"
	echo -e "\e[1;32m*******************\e[0m"
	echo -e ""
	echo -e "\e[1;32m Choose which tools do you want for your custom image \e[0m"
	options=("Vim"
		"Emacs"
		"Return to Previous Menu"
		)

		
		select opt in "${options[@]}"
		do
			case $opt in

			"Vim")
			echo -e "# Vim" >> Dockerfile
			echo "RUN pacman -S vim --noconfirm" >> Dockerfile
			Return_Message
			break
			;;

			"Emacs")
			echo -e "# EMACS" >> Dockerfile
			echo "RUN pacman -Sy && pacman -S  emacs-nox --noconfirm" >> Dockerfile
			Return_Message
			break
			;;

			"Return to Previous Menu")
			break 2
			;;

			*) echo -e "Oops, wrong option, try again"
			;;
			esac
		done
	done
}

"$@"
