#!/usr/bin/env bash
# Python tools for Arch Docker image

Return_Message(){
echo -e "\e[1;37;42mTool Added\e[0m"
echo -e "\e[1;32mIf you want to add some tool more, return to previous menus and hit the option, when you finish, return to previous menu\e[0m"
echo -e "\e[1;32mof pimp my container and choose the let's pimp my image option to build your custom image\e[0m"
sleep 2
}

Javascript_Arch(){
	while true;do
		echo -e "\e[1;32m***********************\e[0m"
		echo -e "\033[5;32m*  Javascript tools  *\033[0m"
		echo -e "\e[1;32m***********************\e[0m"
		echo -e ""
		echo -e "\e[1;32m Choose which tools do you want for your custom image \e[0m"
		options=("npm"
			"Nodejs"
			"Return to Previous Menu")
	
			select opt in "${options[@]}"
			do
				case $opt in

					"npm")
					echo -e "RUN pacman -Sy && pacman -S npm --noconfirm" >> Dockerfile
					Return_Message
					break
					;;

					"Nodejs")
					echo -e "RUN pacman -Sy && pacman -S npm --noconfirm" >> Dockerfile
					echo -e "RUN npm install nodejs" >> Dockerfile
					Return_Message
					break
					;;

					"Return to Previous Menu")
					break 2
					;;

					*) echo -e "Opps, wrong option, try again :)"
					;;
		    		esac

			done
	done

}

"$@"
