#!/usr/bin/env bash
# Python tools for Arch Docker image

Return_Message(){
echo -e "\e[1;37;42mTool Added\e[0m"
echo -e "\e[1;32mIf you want to add some tool more, return to previous menus and hit the option, when you finish, return to previous menu\e[0m"
echo -e "\e[1;32mof pimp my container and choose the let's pimp my image option to build your custom image\e[0m"
sleep 2
}

Arch_PyPip(){
echo -e "RUN pacman -Sy && pacman -S python python-pip --noconfirm" >> Dockerfile
}

Python_Arch(){
	while true;do
		echo -e "\e[1;32m*******************\e[0m"
		echo -e "\033[5;32m*  Python tools  *\033[0m"
		echo -e "\e[1;32m*******************\e[0m"
		echo -e ""
		echo -e "\e[1;32m Choose which tools do you want for your custom image \e[0m"
		options=("Python 3"
			"Pip 3"
			"Flask"
			"Django"
			"Fabric"
			"SQLAlchemy"
			"Return to Previous Menu")
	
			select opt in "${options[@]}"
			do
			case $opt in
			
			"Python 3")
			echo -e "RUN pacman -Sy && pacman -S python --noconfirm" >> Dockerfile
			Return_Message
			break
			;;

			"Pip 3")
			Arch_PyPip
			Return_Message
			break
			;;

			"Flask")
			Arch_PyPip
			echo "RUN pip install Flask" >> Dockerfile
			Return_Message
			break
			;;

			"Django")
			Arch_PyPip
			echo "RUN pip install Django" >> Dockerfile
			break
			;;

			"Fabric")
			Arch_PyPip
			echo "RUN pip install fabric" >> Dockerfile
			Return_Message
			break
			;;

			"SQLAlchemy")
			Arch_PyPip
			echo "RUN pip install SQLAlchemy" >> Dockerfile
			Return_Message
			break
			;;

			"Return to Previous Menu")
			break 2
			;;

			*) echo -e "Opps, wrong option, try again :)"
			;;
    			esac

			done
	done

}

"$@"


