#!/usr/bin/env bash
# Pimp my container
# Developed by David Latorre (LatorreDev)

# Main Execution

Pimp_It(){
	./Bash/Base/Base
}

Install_Requirements(){
	./Bash/reqs/install_reqs
}

Check_Docker(){
	./Bash/Docker/Docker_Service Check_Docker
}

Pimp_Choose_Distro_Base(){
	./Bash/Base/Base
}

Manage_Volumes(){
	./Bash/Volumes/Volumes Manage_Volumes
}

Manage_Images(){
	./Bash/Images/Images Manage_Images
}

Manage_Containers(){
	./Bash/Containers/Containers
}

while true; do
echo -e "\e[1;32m**********************\e[0m"
echo -e "\033[5;32m* Pimp my container  *\033[0m"
echo -e "\e[1;32m**********************\e[0m"
	options=(
		"Install Requirements"
		"Check Docker Service"
		"Pimp my container"
		"Manage Volumes"
		"Manage Images"
		"Manage Containers"
	        "Exit")
		select opt in "${options[@]}"
		do                                                                              
			case $opt in
			"Install Requirements")
			Install_Requirements
			break
			;;

			"Check Docker Service")
			Check_Docker
			break
			;;

			"Pimp my container")
			Pimp_It
			break
			;;

			"Manage Volumes")
			Manage_Volumes
			break
			;;

			"Manage Images")
			Manage_Images
			break
			;;

			"Manage Containers")
			Manage_Containers
			break
			;;

			"Exit")
			echo -e "Time to say goodbye"
			sleep 1
    			break 2
    			;;
			
			*) echo -e "Opps, wrong option, try again :)"
			sleep 1.5
			break
			;;

    		esac
	done
done
